name: uni_walker
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.0
  bloc: ^8.1.2
  camera: ^0.10.5+5
  csv: ^5.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_blue_plus: ^1.18.3
  meta: ^1.9.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  simple_kalman: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/
